version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout      

      - run:
          name: install libs
          command: |
            apt-get update && apt-get -y install git-core gnupg flex bison gperf libsdl-dev libesd0-dev build-essential zip curl libncurses5-dev zlib1g-dev lib32z1-dev lib32ncurses5-dev sharutils lzop wget libssl-dev
            git clone https://github.com/4Fwolf/4.6.x-google_prerelease_toolchain.git toolchains
            wget http://www.haoyuelectronics.com/service/RK3066/tools/linux/rk-tools.zip 
            unzip rk-tools 
            cd rk-tools-master && make && make install && cd ..
 
    
      - run:
          name: Build kernel
          command: |
            export ARCH=arm 
            export CROSS_COMPILE=$PWD/toolchains/arm-eabi-4.6/bin/arm-eabi-
            make -j 4
            
            

   
      - run:
          name: crc kernel and upload
          command: |
            mtime=$(date '+%m_%d_%I_%M_%S_%p')
            mkdir output
            rkcrc -k arch/arm/boot/Image output/kernel_circ_${mtime}.img
            cd output
            cp kernel_circ_${mtime}.img kernel.img
            curl -F "UPLOADCARE_PUB_KEY=aed7fd5dbd403e94035e" -F "UPLOADCARE_STORE=1" -F "file=@kernel_circ_${mtime}.img" "https://upload.uploadcare.com/base/"
     
      - store_artifacts:
          path: ~/project/output
          destination: kernel
